"""
Hierarchical clustering of time series that is represented by an 
image generated by:

1) "time_series_gen.py"
2) "sequential_data_to_image.py"
"""
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
from PIL import Image
import argparse


def main(input_file, output_file):
    data = Image.open(input_file).convert('L')
    data = np.array(data)
    linkage_matrix = linkage(data, method='ward', metric='euclidean')

    fig, (ax1, ax2) = plt.subplots(1, 2, 
                                   figsize=(12, 3), 
                                   gridspec_kw={'width_ratios': [1, 15]})

    dendro = dendrogram(linkage_matrix,
               orientation='left',
               distance_sort='descending',
               show_leaf_counts=False,
               ax=ax1)
    ax1.set_title('Dendrogram')
    ax1.set_ylabel('Sample Index')
    ax1.set_xlabel('Distance')
    ax1.tick_params(axis='y', which='both', labelsize=8)

    reordered_indices = dendro['leaves']
    clustered_data = data[reordered_indices, :]

    ax2.imshow(clustered_data, aspect='auto', cmap='viridis', origin='lower')
    ax2.set_title('Clustered Series')
    ax2.set_xlabel('Time Steps')
    ax2.get_yaxis().set_ticks([])

    plt.tight_layout()
    fig.savefig(output_file)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', '-i', help="Input image.",
                        required=True,
                        type=str,
                        dest='input_file')
    parser.add_argument('--output', '-o',
                        help="Output image with rows clustered.",
                        required=True,
                        type=str,
                        dest='output_file')
    args = parser.parse_args()

    main(args.input_file, args.output_file)